#!/bin/bash -e

# minc-toolkit configuration parameters for 1.9.16-20180117
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$APPDIR/lib"
export MINC_FORCE_V2=1
export MINC_COMPRESS=4
export VOLUME_CACHE_THRESHOLD=-1

exec "$APPDIR/bin/Display" "$@"
